{
 "title": "riffle",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "worker",
    "query": {
     "query": "label_values(memory_used,worker_id)"
    }
   },
   {
    "name": "rateMetrics",
    "query": "total_read_data,\ntotal_read_data_from_localfile,\ntotal_read_index_from_localfile,\ntotal_read_data_from_memory,\n\ntotal_received_data,\ntotal_localfile_used,\ntotal_memory_used,\ntotal_hdfs_used,\n\ntotal_grpc_request_number,"
   },
   {
    "name": "grpcpath",
    "query": {
     "query": "label_values(grpc_duration_seconds_bucket,path)"
    }
   },
   { "name": "requestQps", "query": "total_grpc_request_number" },
   {
    "name": "common",
    "query": "memory_used,\nmemory_allocated,\nmemory_spill_in_flushing_bytes,\nmemory_spill_in_flushing_operations,\nmemory_spill_to_hdfs,\nmemory_spill_to_localfile,\npartition_number,\napp_number,\nlocal_disk_used,\nlocal_disk_used_ratio,\nruntime_thread_alive_gauge,\nruntime_thread_idle_gauge,\ntotal_spill_events_dropped,\ngrpc_request_number,\nprocess_resident_memory_bytes,\nprocess_virtual_memory_bytes,\ntotal_app_number,\ntotal_hdfs_used,\ntotal_huge_partition_require_buffer_failed,\ntotal_localfile_used,\ntotal_memory_used,\ntotal_partition_number,\ntotal_require_buffer_failed,\nallocator_allocated_size,\ntotal_evict_timeout_tickets_num,\nlocal_disk_is_healthy,\nservice_is_healthy,\ntotal_memory_spill_to_hdfs,\ntotal_memory_spill_to_localfile,\ntotal_memory_spill_failed,\ntotal_memory_to_localfile_spill_failed,\ntotal_memory_to_hdfs_spill_failed,\nhuge_partition_number,\ntotal_huge_partition_number,\npurge_failed_count,\ntotal_spill_events_dropped_with_app_not_found,\nresident_bytes,"
   },
   { "name": "interval", "query": "1m,\n20s,\n30s" },
   {
    "name": "localfile_disk_path",
    "query": "/data1/riffle/data,\n/data2/riffle/data,\n/data3/riffle/data,\n/data4/riffle/data,"
   },
   {
    "name": "event_bus_name",
    "query": {
     "query": "label_values(eventbus_queue_pending_size,name)"
    }
   },
   {
    "name": "external_grpc_latency",
    "query": "grpc_get_memory_data_process_time_bucket,\ngrpc_get_memory_data_transport_time_bucket,\ngrpc_send_data_process_time_bucket,\ngrpc_send_data_transport_time_bucket,\ngrpc_get_memory_data_freeze_process_time_bucket,\ngrpc_get_localfile_data_transport_time_bucket,\ngrpc_get_localfile_data_process_time_bucket,"
   },
   {
    "name": "io_scheduler_metrics",
    "query": "read_permits,\nappend_permits,\nshared_permits,\nread_wait,\nappend_wait,"
   }
  ]
 },
 "panels": [
  { "title": "Statistics (cluster level)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPC throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    { "expr": "sum(rate(total_read_data[1m]))", "legendFormat": "read" },
    {
     "expr": "sum(rate(total_received_data[1m]))",
     "legendFormat": "receive"
    },
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "24H total shuffle size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(delta(total_received_data[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(service_is_healthy)", "legendFormat": "unhealthy_servers" },
    { "expr": "sum(local_disk_is_healthy)", "legendFormat": "unhealthy_disks" }
   ]
  },
  {
   "title": "Unhealthy server list",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "service_is_healthy == 1", "legendFormat": "unhealthy_servers" }
   ]
  },
  {
   "title": "HDFS throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    { "expr": "sum(rate(total_hdfs_used[1m]))", "legendFormat": "hdfs write" }
   ]
  },
  {
   "title": "Alive servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(memory_used)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IO scheduler (only for direct IO)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "$io_scheduler_metrics",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "repeat": "io_scheduler_metrics",
     "targets": [
      {
       "expr": "$io_scheduler_metrics{worker_id=~'$worker'}",
       "legendFormat": "{{root}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Web link",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
     "options": {
      "content": "\n| name        | link                                 |\n| ----------- | :----------------------------------- |\n| await-tree  | http://10.77.62.104:20010/await-tree |\n| apps        | http://10.77.62.104:20010/apps       |\n| build infos | http://10.77.62.104:20010            |\n"
     }
    }
   ]
  },
  {
   "title": "Alignment Buffer Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "buffer acquired",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "alignment_buffer_pool_acquired_buffer{worker_id=~\"$worker\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "read buffer miss",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "alignment_buffer_pool_read_acquire_miss{worker_id=~\"$worker\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "buffer missed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "alignment_buffer_pool_acquired_miss{worker_id=~\"$worker\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "App Resident Bytes",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 254 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topN_app_resident_bytes{worker_id=\"$worker\"} > 0",
       "legendFormat": "{{app_id}}"
      }
     ]
    },
    {
     "title": "[LOCALFILE] App Flushed Bytes",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 254 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "app_flushed_bytes{worker_id=\"$worker\", storage_type=\"LOCALFILE\"} > 0",
       "legendFormat": "{{app_id}}"
      }
     ]
    },
    {
     "title": "[HDFS] App Flushed Bytes",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 254 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "app_flushed_bytes{worker_id=\"$worker\", storage_type=\"HDFS\"} > 0",
       "legendFormat": "{{app_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Statistics (server level)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Running Apps",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_number{worker_id=\"$worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alive Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "partition_number{worker_id=\"$worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(total_require_buffer_failed{worker_id=~\"$worker\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_spill_events_dropped{worker_id=\"$worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_used{worker_id=\"$worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(total_grpc_request_number{worker_id=\"$worker\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24 小时 shuffle 总量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(total_received_data{worker_id=\"$worker\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "RPC Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(total_read_data{worker_id=~'$worker'}[1m]) + rate(total_received_data{worker_id=~\"$worker\"}[1m])",
     "legendFormat": "ALL"
    },
    {
     "expr": "rate(total_read_data{worker_id=~'$worker'}[1m])",
     "legendFormat": "READ"
    },
    {
     "expr": "rate(total_received_data{worker_id=~\"$worker\"}[1m])",
     "legendFormat": "WRITE"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(localfile_disk_read_operation_bytes_counter{job=\"uniffle-worker\", worker_id=~\"$worker\"}[1m]) + rate(localfile_disk_append_operation_bytes_counter{ job=\"uniffle-worker\", worker_id=~\"$worker\"}[1m]))",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum(rate(localfile_disk_read_operation_bytes_counter{job=\"uniffle-worker\", worker_id=~\"$worker\"}[1m]))",
     "legendFormat": "READ"
    },
    {
     "expr": "sum(rate(localfile_disk_append_operation_bytes_counter{job=\"uniffle-worker\", worker_id=~\"$worker\"}[1m]))",
     "legendFormat": "WRITE"
    }
   ]
  },
  { "title": "Backpressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "total_require_buffer_failed / 1min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(total_require_buffer_failed{worker_id=~\"$worker\"}[1m])",
     "legendFormat": "x"
    }
   ]
  },
  {
   "title": "total_huge_partition_require_buffer_failed / 1min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(total_huge_partition_require_buffer_failed{worker_id=~\"$worker\"}[1m])",
     "legendFormat": "x"
    }
   ]
  },
  {
   "title": "EventBus - [$event_bus_name]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "event_bus_name",
   "collapsed": true,
   "panels": [
    {
     "title": "event queue",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eventbus_queue_pending_size{name=~\"$event_bus_name\", job=\"uniffle-worker\", worker_id=~\"$worker\"}",
       "legendFormat": "in_pending"
      },
      {
       "expr": "eventbus_queue_handling_size{name=~\"$event_bus_name\", job=\"uniffle-worker\", worker_id=~\"$worker\"}",
       "legendFormat": "in_handling"
      }
     ]
    },
    {
     "title": "event rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(eventbus_total_handled_event_size{name=~\"$event_bus_name\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[1m])",
       "legendFormat": "handled"
      },
      {
       "expr": "rate(eventbus_total_published_event_size{name=~\"$event_bus_name\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[1m])",
       "legendFormat": "published"
      }
     ]
    },
    {
     "title": "event handled time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(eventbus_handle_operation_duration_bucket{name=~\"$event_bus_name\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(eventbus_handle_operation_duration_bucket{name=~\"$event_bus_name\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(eventbus_handle_operation_duration_bucket{name=~\"$event_bus_name\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(eventbus_handle_operation_duration_bucket{name=~\"$event_bus_name\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.4, sum(rate(eventbus_handle_operation_duration_bucket{name=~\"$event_bus_name\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.4"
      }
     ]
    }
   ]
  },
  {
   "title": "Spill",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "spill event bytes histrogram",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6790 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(memory_spill_batch_size_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(memory_spill_batch_size_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(memory_spill_batch_size_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(memory_spill_batch_size_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.2, sum(rate(memory_spill_batch_size_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.2"
      }
     ]
    },
    {
     "title": "memory_spill_in_queue_bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6790 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "memory_spill_in_queue_bytes{worker_id=~\"$worker\"}",
       "legendFormat": "x"
      }
     ]
    },
    {
     "title": "memory_spill_in_flushing_bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6790 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "memory_spill_in_flushing_bytes{worker_id=~\"$worker\", storage_type=\"LOCALFILE\"}",
       "legendFormat": "x"
      }
     ]
    },
    {
     "title": "memory_spill_in_flushing_operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6790 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "memory_spill_in_flushing_operations{worker_id=~\"$worker\"}",
       "legendFormat": "x"
      }
     ]
    },
    {
     "title": "[LOCALFILE] event bytes histrogram",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6796 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(memory_spill_in_flushing_bytes_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\", storage_type=\"LOCALFILE\"}[$interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(memory_spill_in_flushing_bytes_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\", storage_type=\"LOCALFILE\"}[$interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(memory_spill_in_flushing_bytes_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\", storage_type=\"LOCALFILE\"}[$interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(memory_spill_in_flushing_bytes_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\", storage_type=\"LOCALFILE\"}[$interval])) by (le))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.2, sum(rate(memory_spill_in_flushing_bytes_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\", storage_type=\"LOCALFILE\"}[$interval])) by (le))",
       "legendFormat": "0.2"
      }
     ]
    },
    {
     "title": "[HDFS] event bytes histrogram",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6796 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(memory_spill_in_flushing_bytes_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\", storage_type=\"HDFS\"}[$interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(memory_spill_in_flushing_bytes_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\", storage_type=\"HDFS\"}[$interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(memory_spill_in_flushing_bytes_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\", storage_type=\"HDFS\"}[$interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(memory_spill_in_flushing_bytes_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\", storage_type=\"HDFS\"}[$interval])) by (le))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.2, sum(rate(memory_spill_in_flushing_bytes_histogram_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\", storage_type=\"HDFS\"}[$interval])) by (le))",
       "legendFormat": "0.2"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "[all bps] $localfile_disk_path",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4505 },
     "repeat": "localfile_disk_path",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(localfile_disk_read_operation_bytes_counter{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval]) + rate(localfile_disk_append_operation_bytes_counter{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])",
       "legendFormat": "x"
      }
     ]
    },
    {
     "title": "[append] $localfile_disk_path",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4509 },
     "repeat": "localfile_disk_path",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(localfile_disk_append_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(localfile_disk_append_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(localfile_disk_append_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(localfile_disk_append_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "[read] $localfile_disk_path",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4513 },
     "repeat": "localfile_disk_path",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(localfile_disk_read_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(localfile_disk_read_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(localfile_disk_read_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(localfile_disk_read_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "[direct read] $localfile_disk_path",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4517 },
     "repeat": "localfile_disk_path",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(localfile_disk_direct_read_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(localfile_disk_direct_read_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(localfile_disk_direct_read_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(localfile_disk_direct_read_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$interval])) by (le))",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "[delete] $localfile_disk_path",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4527 },
     "repeat": "localfile_disk_path",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(localfile_disk_delete_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(localfile_disk_delete_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(localfile_disk_delete_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(localfile_disk_delete_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "[stat] $localfile_disk_path",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4531 },
     "repeat": "localfile_disk_path",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(localfile_disk_stat_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(localfile_disk_stat_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(localfile_disk_stat_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(localfile_disk_stat_operation_duration_bucket{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "[append iops] $localfile_disk_path",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4535 },
     "repeat": "localfile_disk_path",
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(localfile_disk_append_operation_counter{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])",
       "legendFormat": "x"
      }
     ]
    },
    {
     "title": "[append bps] $localfile_disk_path",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4539 },
     "repeat": "localfile_disk_path",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(localfile_disk_append_operation_bytes_counter{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])",
       "legendFormat": "x"
      }
     ]
    },
    {
     "title": "[read iops] $localfile_disk_path",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4543 },
     "repeat": "localfile_disk_path",
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(localfile_disk_read_operation_counter{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])",
       "legendFormat": "x"
      }
     ]
    },
    {
     "title": "[read bps] $localfile_disk_path",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4547 },
     "repeat": "localfile_disk_path",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(localfile_disk_read_operation_bytes_counter{root=~\"$localfile_disk_path\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])",
       "legendFormat": "x"
      }
     ]
    }
   ]
  },
  {
   "title": "QPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "qps",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12742 },
     "targets": [
      {
       "expr": "rate($requestQps{worker_id=~'$worker'}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "URPC Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "urpc_send_data_process_time",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7158 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(urpc_send_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(urpc_send_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(urpc_send_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(urpc_send_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "upc_send_data_transport_time",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7158 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(urpc_send_data_transport_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(urpc_send_data_transport_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(urpc_send_data_transport_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(urpc_send_data_transport_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "urpc_get_memory_data_process_time",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7158 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(urpc_get_memory_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(urpc_get_memory_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(urpc_get_memory_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(urpc_get_memory_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "urpc_get_localfile_data_process_time",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7158 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(urpc_get_localfile_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.99"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(urpc_get_localfile_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.9"
      },
      {
       "expr": "histogram_quantile(0.8, sum(rate(urpc_get_localfile_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.8"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(urpc_get_localfile_data_process_time_bucket{job=\"uniffle-worker\"}[$interval])) by (le))",
       "legendFormat": "0.5"
      }
     ]
    },
    {
     "title": "urpc_connection_number",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7166 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "urpc_connection_number{job=\"uniffle-worker\"}",
       "legendFormat": "0.99"
      }
     ]
    }
   ]
  },
  { "title": "GRPC Latency [external]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "$external_grpc_latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 49 },
   "repeat": "external_grpc_latency",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate($external_grpc_latency{job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate($external_grpc_latency{job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate($external_grpc_latency{job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.8"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate($external_grpc_latency{job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  { "title": "GRPC Latency [general]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "$grpcpath",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 58 },
   "repeat": "grpcpath",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_duration_seconds_bucket{path=~\"$grpcpath\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_duration_seconds_bucket{path=~\"$grpcpath\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(grpc_duration_seconds_bucket{path=~\"$grpcpath\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(grpc_duration_seconds_bucket{path=~\"$grpcpath\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.8"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_duration_seconds_bucket{path=~\"$grpcpath\", job=\"uniffle-worker\", worker_id=~\"$worker\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Local Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "grpc_get_localfile_data_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4016 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "grpc_get_localfile_data_latency{worker_id=~\"$worker\", quantile=\"p99\"}",
       "legendFormat": "p99"
      },
      {
       "expr": "grpc_get_localfile_data_latency{worker_id=~\"$worker\", quantile=\"p95\"}",
       "legendFormat": "p95"
      },
      {
       "expr": "grpc_get_localfile_data_latency{worker_id=~\"$worker\", quantile=\"p90\"}",
       "legendFormat": "p90"
      },
      {
       "expr": "grpc_get_localfile_data_latency{worker_id=~\"$worker\", quantile=\"p80\"}",
       "legendFormat": "p80"
      },
      {
       "expr": "grpc_get_localfile_data_latency{worker_id=~\"$worker\", quantile=\"p50\"}",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "grpc_get_localfile_index_latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4016 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "grpc_get_localfile_index_latency{worker_id=~\"$worker\", quantile=\"p99\"}",
       "legendFormat": "p99"
      },
      {
       "expr": "grpc_get_localfile_index_latency{worker_id=~\"$worker\", quantile=\"p95\"}",
       "legendFormat": "p95"
      },
      {
       "expr": "grpc_get_localfile_index_latency{worker_id=~\"$worker\", quantile=\"p90\"}",
       "legendFormat": "p90"
      },
      {
       "expr": "grpc_get_localfile_index_latency{worker_id=~\"$worker\", quantile=\"p80\"}",
       "legendFormat": "p80"
      },
      {
       "expr": "grpc_get_localfile_index_latency{worker_id=~\"$worker\", quantile=\"p50\"}",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "[Read] disk latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4022 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(localfile_disk_read_operation_duration_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[20s])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(localfile_disk_read_operation_duration_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[20s])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(localfile_disk_read_operation_duration_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[20s])) by (le))",
       "legendFormat": "p90"
      }
     ]
    },
    {
     "title": "[Direct read] disk latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4022 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(localfile_disk_direct_read_operation_duration_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[20s])) by (le))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(localfile_disk_direct_read_operation_duration_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[20s])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(localfile_disk_direct_read_operation_duration_bucket{job=\"uniffle-worker\", worker_id=~\"$worker\"}[20s])) by (le))",
       "legendFormat": "p90"
      }
     ]
    }
   ]
  },
  { "title": "Write/Read Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "$rateMetrics",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 72 },
   "repeat": "rateMetrics",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate($rateMetrics{worker_id=~'$worker'}[1m])",
     "legendFormat": "{{worker_id}}"
    }
   ]
  },
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "$common",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 83 },
   "repeat": "common",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "$common{worker_id=~'$worker'}", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}