#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.2"
      - uses: actions/checkout@v3
      - name: Code style check
        working-directory: ./
        run: cargo fmt --check

  build_with_features:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
        features:
          - "--features memory-prof"
          - ""
    runs-on: ${{ matrix.os }}
    steps:
      - name: Remove unnecessary files (Linux only)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.2"
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Build
        working-directory: ./
        run: cargo build ${{ matrix.features }} --release
      - name: Unit tests
        working-directory: ./
        run: cargo test --verbose ${{ matrix.features }} -- --test-threads=1

  with-hdrs:
    runs-on: ubuntu-22.04
    steps:
      - name: Remove unnecessary files (Linux only)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: actions/checkout@v4

      - name: Build
        run: docker compose -f dev/centos7/amd64/docker-compose.yml up